[metadata]
name = fastreer
version = 1.13.24
author = Anestis Gkanogiannis
author_email = anestis@gkanogiannis.com
description = CLI toolkit for phylogenetic trees and distance matrices from VCF and FASTA
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/gkanogiannis/fastreeR
license = GPL-3
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.7
include_package_data = True

[options.entry_points]
console_scripts =
    fastreeR = fastreer.cli:main

[console_scripts]
fastreeR = fastreer.cli:main
