name: fastreer_vcf2dist
owner: gkanogiannis
description: Build cosine distance matrix from VCF(s) using fastreeR
homepage_url: https://github.com/gkanogiannis/fastreeR
remote_repository_url: https://github.com/gkanogiannis/fastreeR
long_description: >
  Galaxy wrapper for the VCF2DIST command of fastreeR (Java CLI, Bioconda and BioConductor package).
type: unrestricted
