categories:
- Phylogenetics
name: fastreer_vcf2tree
owner: gkanogiannis
description: Build neighbor joining phylogenetic tree (dendrogram) from VCF(s) using fastreeR
homepage_url: https://github.com/gkanogiannis/fastreeR
remote_repository_url: https://github.com/gkanogiannis/fastreeR
long_description: >
  Galaxy wrapper for the VCF2TREE command of fastreeR (Java CLI, Bioconda and BioConductor package).
type: unrestricted
