categories:
- Phylogenetics
name: fastreer_dist2tree
owner: gkanogiannis
description: Build neighbor joining phylogenetic tree from distance matrix using fastreeR
homepage_url: https://github.com/gkanogiannis/fastreeR
remote_repository_url: https://github.com/gkanogiannis/fastreeR
long_description: >
  Galaxy wrapper for the DIST2TREE command of fastreeR (Java CLI, Bioconda and BioConductor package).
type: unrestricted
