name: Publish to Galaxy ToolShed

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-toolshed:
    name: Publish to Galaxy ToolShed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Planemo
        run: pip install planemo

      - name: Upload tools to ToolShed
        env:
          PLANEMO_TOOLSHED_API_KEY: ${{ secrets.GALAXY_TOOLSHED_API_KEY }}
        run: |
          make galaxy-update-toolshed TOOLSHED_KEY=${PLANEMO_TOOLSHED_API_KEY}
