name: Galaxy Tool Tests

on:
  workflow_dispatch:

jobs:
  test-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Planemo
        run: |
          pip install planemo
          planemo --version

      - name: Run tool tests
        run: |
          make galaxy-test-tools

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fastreer-galaxy-test-report
          path: "**galaxy/**/galaxy-test-report.html"
          overwrite: true
